# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190412_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top',
            field=models.CharField(default=0, max_length=2, verbose_name='文章置顶'),
        ),
    ]
