# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_blog_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.TextField(default='http://127.0.0.1:8080/gg/picture/1903051025511551752751166329.jpg', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
