# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190412_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='watch',
            field=models.CharField(default=0, max_length=100, verbose_name='观看人数'),
        ),
    ]
