# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='男', max_length=3, verbose_name='性别'),
        ),
    ]
