# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.CharField(default='http://127.0.0.1:8080/gg/update/HeadPortrait/1904081148091554695289943283.jpg', max_length=300, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(default='他还没有介绍自己。。。', max_length=300, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='无', max_length=10, verbose_name='职业'),
        ),
    ]
