# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190410_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(default='博员', max_length=10, verbose_name='职业'),
        ),
    ]
