# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190410_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
