# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190410_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.TextField(default='http://127.0.0.1:8080/gg/update/HeadPortrait/1904081148091554695289943283.jpg', verbose_name='图片'),
        ),
    ]
