# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190413_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='http://127.0.0.1:8080/gg/update/HeadPortrait/1904081148091554695289943283.jpg', null=True, upload_to='icons', verbose_name='图片'),
        ),
    ]
