# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-14 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190413_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='Fo8HIkDewVPK4jrSAEzk0vrdxW5H', null=True, upload_to='', verbose_name='图片'),
        ),
    ]
