# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-14 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190414_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userz_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '申请发布博客用户',
                'verbose_name_plural': '申请发布博客用户',
                'db_table': 'tb_users_apply',
            },
        ),
    ]
