# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userz_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bolg_sid',
            field=models.CharField(default=0, max_length=2, verbose_name='发布博客权限'),
        ),
    ]
