# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrator',
            field=models.CharField(default=0, max_length=2, verbose_name='管理员'),
        ),
    ]
